config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'food_racks#index'
  resources :food_racks do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '冷蔵庫' },
    { id: 3, name: '食品棚A' },
    { id: 4, name: '食品棚B' },
  ]

  include ActiveHash::Associations
  has_many :food_racks
end

app/models/day.rb
class Day < ActiveHash::Base
  self.data = [
    { id: 1, name: '-日-' },
    { id: 2, name: '１日' },
    { id: 3, name: '２日' },
    { id: 4, name: '３日' },
    { id: 5, name: '４日' },
    { id: 6, name: '５日' },
    { id: 7, name: '６日' },
    { id: 8, name: '７日' },
    { id: 9, name: '８日' },
    { id: 10, name: '９日' },
    { id: 11, name: '１０日' },
    { id: 12, name: '１１日' },
    { id: 13, name: '１２日' },
    { id: 14, name: '１３日' },
    { id: 15, name: '１４日' },
    { id: 16, name: '１５日' },
    { id: 17, name: '１６日' },
    { id: 18, name: '１７日' },
    { id: 19, name: '１８日' },
    { id: 20, name: '１９日' },
    { id: 21, name: '２０日' },
    { id: 22, name: '２１日' },
    { id: 23, name: '２２日' },
    { id: 24, name: '２３日' },
    { id: 25, name: '２４日' },
    { id: 26, name: '２５日' },
    { id: 27, name: '２６日' },
    { id: 28, name: '２７日' },
    { id: 29, name: '２８日' },
    { id: 30, name: '２９日' },
    { id: 31, name: '３０日' },
    { id: 32, name: '３１日' },
  ]
    include ActiveHash::Associations
    has_many :food_racks
end

app/models/food_rack.rb
class FoodRack < ApplicationRecord
  belongs_to :user
  has_one_attached :picture

  def was_attached?
    self.image.attached?
  end

  def previous
    FoodRack.where("id < ?", self.id).order("id DESC").first
  end
  def next
    FoodRack.where("id > ?", self.id).order("id ASC").first
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :year
  belongs_to :month
  belongs_to :day

  validates :picture, presence: true
  validates :category_id, numericality: { other_than: 1 }
  validates :year_id, numericality: { other_than: 1 }
  validates :month_id, numericality: { other_than: 1 }
  validates :day_id, numericality: { other_than: 1 }
end

app/models/month.rb
class Month < ActiveHash::Base
  self.data = [
   { id: 1, name: '-月-' },
   { id: 2, name: '１月' },
   { id: 3, name: '２月' },
   { id: 4, name: '３月' },
   { id: 5, name: '４月' },
   { id: 6, name: '５月' },
   { id: 7, name: '６月' },
   { id: 8, name: '７月' },
   { id: 9, name: '８月' },
   { id: 10, name: '９月' },
   { id: 11, name: '１０月' },
   { id: 12, name: '１１月' },
   { id: 13, name: '１２月' },
  ]
   include ActiveHash::Associations
   has_many :food_racks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :food_racks
  has_many :events
end

app/models/year.rb
class Year < ActiveHash::Base
  self.data = [
   { id: 1, name: '-年-' },
   { id: 2, name: '2021年' },
   { id: 3, name: '2022年' },
   { id: 4, name: '2023年' },
   { id: 5, name: '2024年' },
   { id: 6, name: '2025年' },
   { id: 7, name: '2026年' },
   { id: 8, name: '2027年' },
  ]
   include ActiveHash::Associations
   has_many :food_racks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:first_name_kana,:last_name_kana,:age,:gender])
  end
end

app/controllers/food_racks_controller.rb
class FoodRacksController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_food_rack, only: [:edit, :show, :update, :destroy]
 
  def index
    @food_racks = FoodRack.order("created_at DESC")
  end

  def new
    @food_rack = FoodRack.new
  end

  def create
    @food_rack = FoodRack.new(foodrack_params)
    if @food_rack.valid?
      @food_rack.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @food_rack.update(foodrack_params)
      redirect_to food_rack_path, method: :get
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @food_rack.user_id
      redirect_to root_path if @food_rack.destroy
    end
  end

  def show
    @food_rack = FoodRack.find(params[:id])
  end

  private

  def foodrack_params
    params.require(:food_rack).permit(:food_name,:picture,:category_id,:year_id, :month_id,:day_id,:memo).merge(user_id: current_user.id)
  end

  def set_food_rack
    @food_rack = FoodRack.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_racks_helper.rb
module FoodRacksHelper
end

app/views/food_racks/edit.html.erb
<%# cssは商品出品のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="foodracks-contents">
  <header class="foodracks-header">
    <%= link_to root_path do %>
      <span class='logo-btn-text'>FOODS REMIND</span>
      <%= image_tag 'information-160948__480吹き出し.webp' , size: '185x50' %>
    <% end %>
  </header>
  <div class="foodracks-main">
    <h2 class="foodracks-title">食材の情報を入力</h2>
    <%= form_with(model:@food_rack,local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        食材の写真
        <span class="indispensable1">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :picture, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        食材の名前
      </div>
      <%= f.text_area :food_name, class:"items-text", id:"item-name", placeholder:"食材の名前(20文字まで)", maxlength:"20" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          メモ
        </div>
        <%= f.text_area :memo, class:"items-text", id:"item-info", placeholder:"100文字まで（特徴、素材、定価、注意点など自由にご記入ください）　例）やや辛い、国産、200円、賞味期限短い" ,rows:"7" ,maxlength:"100" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          保存場所
          <span class="indispensable1">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>

        <div class="weight-bold-text">
          賞味期限・消費期限
          <span class="indispensable1">必須</span>
        </div>
        <%= f.collection_select(:year_id, Year.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <%= f.collection_select(:month_id, Month.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>
    <div class="regist-btn-contents">
      <%= f.submit "食材を登録する" ,class:"regist-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
    <p class="inc">
      Foods Remind
    </p>
  </footer>
</div>

app/views/food_racks/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='title-contents'>
    <h2 class='service-title'>
      長期保存食材の管理
    </h2>
    <div class='service-explain'>
      食材棚や冷蔵庫の奥に秘められた食材達を管理します
    </div>
  </div>
  <div class='foodracks-contents'>
    <h2 class='title'>食材リスト</h2>
    <ul class='foodracks-lists'>
      <% if user_signed_in? %>
        <% @food_racks.each do |food_rack|%>
            <% if current_user.id == food_rack.user_id %>
              <li class='list'>

                <%= link_to food_rack_path(food_rack.id),method: :get do %>
                <div>
                  <%= image_tag food_rack.picture, class: "foodracks-img" %>
                </div>
                <div class='foodracks-info'>
                  <h3 class='foodracks-name'>
                    食材名:　<%= food_rack.food_name %>
                  </h3>
                  <div class='foodracks-memo'>
                    メモ:　<%= food_rack.memo %>
                    <br>保存場所:　<%= food_rack.category.name %>
                    <br>賞味期限・消費期限:　<%= food_rack.year.name %><%= food_rack.month.name %><%= food_rack.day.name %>
                  </div>
                </div>
                <% end %>
              </li>
            <% end %>
          <% end %>
      <% else %>
          <li class='list'>
            <%= link_to '#' do %>
            <%= image_tag "チキンラーメン.jpg", class: "food-img" %>
            <div class='food-info'>
              <h3 class='food-name'>
                <p>食材を登録してください</p>
              </h3>
              <div class='food-memo'>
                <p>メモ:</p><%= "美味い" %>
                <br><p>保存場所:</p><%= "食材棚A" %>
                <br></p>賞味期限・消費期限:</p><%= "２月６日" %>
              </div>
            </div>
            <% end %>
          </li>
      <% end %>
    </ul>
  </div>
</div>
<%= link_to(new_food_rack_path, class: 'save-btn') do %>
  <span class='save-btn-text'>食材を追加</span>
  <%= image_tag 'tomato-4984619_1280.png' , size: '185x50' ,class: "save-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/food_racks/new.html.erb
<div class="foodracks-contents">
  <header class="foodracks-header">
    <%= link_to root_path do %>
      <span class='logo-btn-text'>FOODS REMIND</span>
      <%= image_tag 'information-160948__480吹き出し.webp' , size: '185x50' %>
    <% end %>
  </header>
  <div class="foodracks-main">
    <h2 class="foodracks-title">食材の情報を入力</h2>
    <%= form_with(model:@food_rack,local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        食材の写真
        <span class="indispensable1">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :picture, id:"item-image" %>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        食材の名前
      </div>
      <%= f.text_area :food_name, class:"items-text", id:"item-name", placeholder:"食材の名前(20文字まで)", maxlength:"20" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          メモ
        </div>
        <%= f.text_area :memo, class:"items-text", id:"item-info", placeholder:"100文字まで（特徴、素材、定価、注意点など自由にご記入ください）　例）やや辛い、国産、200円、賞味期限短い" ,rows:"7" ,maxlength:"100" %>
      </div>
    </div>

    <div class="items-detail">
      <div class="form">
        <div class="weight-bold-text">
          保存場所
          <span class="indispensable1">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>

        <div class="weight-bold-text">
          賞味期限・消費期限
          <span class="indispensable1">必須</span>
        </div>
        <%= f.collection_select(:year_id, Year.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <%= f.collection_select(:month_id, Month.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <%= f.collection_select(:day_id, Day.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      </div>
    </div>
    <div class="regist-btn-contents">
      <%= f.submit "食材を登録する" ,class:"regist-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
    <p class="inc">
      Foods Remind
    </p>
  </footer>
</div>

app/views/food_racks/search.html.erb
<%= form_with(url: search_food_racks_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, class: "input-box" %>
    <%= form.submit "検索",class: "search-button" %>
<% end %>
<div class="contents row">
  <% @food_racks.each do |food_rack| %>
    <%= render partial: "food_rack", locals: { food_rack: food_rack } %>
  <% end %>
</div>

app/views/food_racks/show.html.erb
<%= render "shared/header" %>

<div class="food-show">
  <div class="food-box">
    <div class='item-img-content'>
      <%= image_tag @food_rack.picture ,class:"food-box-img" %>
    </div>
      <%= link_to '情報の変更', edit_food_rack_path, method: :get, class: "food-btn" %>
      <%= link_to 'ごみ箱へ', food_rack_path, method: :delete, class:'food-destroy' %>
      <%= link_to 'メインページへ', root_path, class:'food-destroy' %>
    <div class="food-explain-box">
      <span><%= "食材情報" %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-food">食材の名前</th>
          <td class="detail-value"><%= @food_rack.food_name %></td>
        </tr>
        <tr>
          <th class="detail-food">メモ</th>
          <td class="detail-value"><%= @food_rack.memo %></td>
        </tr>
        <tr>
          <th class="detail-food">保存場所</th>
          <td class="detail-value"><%= @food_rack.category.name %></td>
        </tr>
        <tr>
          <th class="detail-food">賞味期限・消費期限</th>
          <td class="detail-value"><%= @food_rack.year.name %><%= @food_rack.month.name %><%= @food_rack.day.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="option">
    </div>
  </div>
  <div class="links">
    <% if @food_rack.previous.present? && current_user.id == @food_rack.user_id %>
      <%= link_to "前の食材", food_rack_path(@food_rack.previous), class: "prev-food-left-btn"%>
    <% end %>
    <% if @food_rack.next.present? && current_user.id == @food_rack.user_id%>
      <%= link_to "次の食材",food_rack_path(@food_rack.next), class: "next-food-right-btn" %>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Foods Remind</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class= 'background'>
  <div class="inc">
      Foods Remind
  </div>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='logo-contents'>
    <%= link_to(root_path, class: 'logo-btn') do %>
      <span class='logo-btn-text'>FOODS REMIND</span>
      <%= image_tag 'information-160948__480吹き出し.webp' , size: '185x50' ,class: "logo-btn-icon" %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.name, "#", class: "user-name" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録 ', user_registration_path, method: :post, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <%# <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div> %>
  <%#= link_to "FOODS REMIND", "/" %>
  <%# <p class="inc">
    Foods Remind
  </p>
  <%#= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to(root_path, class: 'logo2-btn') do %>
    <span class='logo2-btn-text'>FOODS REMIND</span>
    <%= image_tag 'information-160948__480吹き出し.webp' , size: '185x50' ,class: "logo2-btn-icon" %>
  <% end %>
</header>